name: Build for AMD/Intel
on:
  schedule:
    # build twice a week (20 minutes after last ublue images start building)
    - cron: "00 17 * * 2,4" # build at 17:00 UTC every Tuesday & Thursday
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - ".editorconfig"
      - "resources/**"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - ".editorconfig"
      - "resources/**"
  workflow_dispatch: # allow manually triggering builds
concurrency:
  # only run one build at a time
  group: ${{ github.ref || github.run_id }}
  cancel-in-progress: true
jobs:
  bluebuild:
    name: Build Custom Image AMD-Intel
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      # the build is fully handled by the reusable github action
      - name: Build Custom Image AMD-Intel
        uses: blue-build/github-action@v1.8
        with:
          recipe: amd-intel.yml
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}

          maximize_build_space: true
